import type { Project } from "../../../types/portfolio";

export const projects: Project[] = [
  {
    name: `Proszę tańcz`,
    clientName: "Dawid Kwiatkowski / Kayah",
    director: "Tomek Wilczyński",
    dop: "Piotr Kosmalski",
    fullVideoUrl: "https://www.youtube.com/watch?v=ZHMxzwOSkIU",
    thumbSrc: "prosze_tancz",
  },
  {
    name: `Piegi`,
    clientName: "Otsochodzi",
    director: "Mac Adamczak",
    dop: "Aleksy Kubiak",
    fullVideoUrl: "https://www.youtube.com/watch?v=kXeNzSWxDmA",
    thumbSrc: "piegi",
  },
  {
    name: `Zdrowa księgowość`,
    clientName: "TVC: Infakt",
    director: "Mac Adamczak",
    dop: "Maciej Ryter",
    fullVideoUrl: "https://www.youtube.com/watch?v=zyXzkmzrRVc",
    thumbSrc: "infakt",
  },
  {
    name: `Windows 11 Pro`,
    clientName: "x-kom / Microsoft",
    director: "Tomek Wilczyński",
    dop: "Dima Zinych",
    fullVideoUrl: "https://www.youtube.com/watch?v=MWSsUxALs0w",
    thumbSrc: "windows",
  },
  {
    name: `Listy do M.6\n- rozstania i powroty`,
    clientName: "TVN Discovery Warner Bros.",
    director: "Jan Steifer",
    dop: "Stasiek Wójcik",
    fullVideoUrl: "https://www.youtube.com/watch?v=tzSzi1fw8LI",
    thumbSrc: "listy",
  },
  {
    name: `Widok`,
    clientName: "Jan Rapowanie / Frankleen\n/ 2020",
    director: "Mac Adamczak",
    dop: "Montell Taraschewski",
    fullVideoUrl: "https://www.youtube.com/watch?v=zJk3HJUfEus",
    thumbSrc: "widok",
  },
  {
    name: `Błękit`,
    clientName: "Roxie",
    director: "Tomek Wilczyński",
    dop: "Dima Zinych",
    fullVideoUrl: "https://www.youtube.com/watch?v=ml9Ktn073So",
    thumbSrc: "blekit",
  },
  {
    name: `Michał Sikorski\nx Szymon Majewski`,
    clientName: "x-kom",
    director: "Tomek Wilczyński",
    dop: "Montell Taraschewski",
    fullVideoUrl: "https://www.instagram.com/reel/DDG38iVIOoV/",
    thumbSrc: "xkom",
  },
  {
    name: `Od nowa`,
    clientName: "Kwiat Jabłoni",
    director: "Rodzeństwo Ejryszew (DRAŻE) ",
    dop: "Łukasz Łatanik / Wiktor Ejryszew",
    fullVideoUrl: "https://www.youtube.com/watch?v=HMIbm_l0nMg",
    thumbSrc: "odnowa",
  },
  {
    name: `Milczysz`,
    clientName: "Julia Wieniawa",
    director: "Maciej Aleksander Bierut",
    dop: "Karol Łakomiec",
    fullVideoUrl: "https://www.youtube.com/watch?v=34454W2JG1c",
    thumbSrc: "milczysz",
  },
  {
    name: `Prosimy dotykać`,
    clientName: "Cheetos",
    director: "Marek Sobkiewicz-Hirsch",
    dop: "Dima Zinych",
    fullVideoUrl: "https://www.youtube.com/watch?v=AWR-bck1Ul8",
    thumbSrc: "cheetos",
  },
  {
    name: `Beze mnie`,
    clientName: "Dawid Kwiatkowski",
    director: "Tomek Wilczyński",
    dop: "Dima Zinych",
    fullVideoUrl: "https://www.youtube.com/watch?v=J1A7lFi16hg",
    thumbSrc: "bezemnie",
  },
  {
    name: `#MATA2040`,
    clientName: "MATA",
    director: "Tomek Wilczyński",
    dop: "Adam Andrzejewski",
    fullVideoUrl: "https://www.youtube.com/watch?v=bhv0jkADve8",
    thumbSrc: "mata",
  },
  {
    name: `Bliżej`,
    clientName: "Natalia Kukulska",
    director: "Daniel Jaroszek",
    dop: "Mateusz Dziekoński",
    fullVideoUrl: "https://www.youtube.com/watch?v=JUEe70iQBDc",
    thumbSrc: "blizej",
  },
  {
    name: `Dziewczyna z walizką`,
    clientName: "48HFP /\n77. Festiwal Filmowy w Cannes",
    director: "Tomek Wilczyński",
    dop: "Stasiek Wójcik",
    fullVideoUrl: "https://www.youtube.com/watch?v=4DTFXpAZ6bg",
    thumbSrc: "walizka",
  },
];
